name: Deploy Frontend to S3 (recommended)

on:
  push:
    branches: [ main ]
    paths:
      - 'FrontEnd/**'
  workflow_dispatch:   # allows manual run from Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: FrontEnd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: FrontEnd/package-lock.json

      - name: Install frontend deps
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Configure AWS credentials (for aws cli)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync dist to S3 (remove old files)
        run: aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Ensure index.html is not cached (so browsers fetch new JS hashes)
        run: |
          aws s3 cp dist/index.html s3://${{ secrets.S3_BUCKET }}/index.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"
